version: '3.1'

services:
  app:
    image: 'sha256:ebc433293d6c3ff5c3c1947faf211fd50559ee76778bfeaf5aa16c70fe0e53cd'
    container_name: app
    expose:
      - '8081'
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/file_storage?currentSchema=public
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_DB=file_storage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=local
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'