--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

-- Started on 2024-07-29 23:58:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16684)
-- Name: file_storage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.file_storage (
    id bigint NOT NULL,
    file bytea,
    title character varying(30),
    creation_date timestamp without time zone,
    description character varying(100)
);


ALTER TABLE public.file_storage OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16692)
-- Name: file_storage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.file_storage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.file_storage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4833 (class 0 OID 16684)
-- Dependencies: 215
-- Data for Name: file_storage; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.file_storage (id, file, title, creation_date, description) VALUES (3, '\x69b7', 'test.txt', '2024-07-27 00:00:00', 'описание');
INSERT INTO public.file_storage (id, file, title, creation_date, description) VALUES (4, '\x616263', 'test.txt', '2024-07-27 00:00:00', 'описание');
INSERT INTO public.file_storage (id, file, title, creation_date, description) VALUES (5, '\x69b7', 'test.txt', '2024-07-27 00:00:00', 'описание');
INSERT INTO public.file_storage (id, file, title, creation_date, description) VALUES (6, '\x69b7', 'test.txt', '2024-07-27 00:00:00', 'описание');
INSERT INTO public.file_storage (id, file, title, creation_date, description) VALUES (7, '\x48656c6c6f20776f726c64', 'test.txt', '2024-07-28 00:00:00', 'описание');
INSERT INTO public.file_storage (id, file, title, creation_date, description) VALUES (8, '\x48656c6c6f20776f726c64', 'test.txt', '2024-07-28 00:00:00', 'описание');
INSERT INTO public.file_storage (id, file, title, creation_date, description) VALUES (9, '\x48656c6c6f20776f726c64', 'test.txt', '2024-07-28 20:04:35.43', 'описание');
INSERT INTO public.file_storage (id, file, title, creation_date, description) VALUES (10, '\x48656c6c6f20776f726c64', 'test.txt', '2024-07-28 20:05:54.209', 'описание');
INSERT INTO public.file_storage (id, file, title, creation_date, description) VALUES (11, '\x48656c6c6f20776f726c64', 'test.txt', '2024-07-28 20:15:13.7', 'описание');
INSERT INTO public.file_storage (id, file, title, creation_date, description) VALUES (12, '\x48656cb1fb1f6c6f20776f726c64', 'test.txt', '2024-07-28 20:15:18.956', 'описание');
INSERT INTO public.file_storage (id, file, title, creation_date, description) VALUES (13, '\x546869732d69732d612d736563726574', 'test2.txt', '2024-07-29 01:06:59.75', 'описание теста');
INSERT INTO public.file_storage (id, file, title, creation_date, description) VALUES (14, '\x7b226b6964223a2263623234613339362d343431342d343739332d62346365222c22747970223a224a5754222c22616c67223a224853323536227d', 'test3.txt', '2024-07-29 01:07:26.634', 'описание');


--
-- TOC entry 4840 (class 0 OID 0)
-- Dependencies: 216
-- Name: file_storage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.file_storage_id_seq', 14, true);


--
-- TOC entry 4689 (class 2606 OID 16690)
-- Name: file_storage file_storage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.file_storage
    ADD CONSTRAINT file_storage_pkey PRIMARY KEY (id);


-- Completed on 2024-07-29 23:58:35

--
-- PostgreSQL database dump complete
--

